<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="hyldesigner"
    nsURI="http://mdse.hylstudio.cn/hyldesigner"
    nsPrefix="hyldesigner">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Project">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="containsDomain"
        upperBound="-1"
        eType="#//DomainEntity"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="containsPayload"
        upperBound="-1"
        eType="#//RequestPayload"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dbentity"
        upperBound="-1"
        eType="#//DbEntity"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="responseresult"
        upperBound="-1"
        eType="#//ResponseResult"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="controller"
        upperBound="-1"
        eType="#//Controller"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DomainAttr"
      eSuperTypes="#//Attr">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="isBizKey"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations
          source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details
            key="desc"
            value="是否业务主键"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="optional"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations
          source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details
            key="desc"
            value="是否业务主键"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DbAttr"
      eSuperTypes="#//Attr">
    <eAnnotations
        source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details
          key="desc"
          value="是否业务主键"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RequestAttr"
      eSuperTypes="#//Attr">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dto"
        upperBound="-1"
        eType="#//Dto"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ResponseAttr"
      eSuperTypes="#//Attr">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dto"
        upperBound="-1"
        eType="#//Dto"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DtoAttr"
      eSuperTypes="#//Attr"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Attr"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="key"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="desc"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DomainEntity">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="domainattr"
        upperBound="-1"
        eType="#//DomainAttr"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="generate"
        upperBound="-1"
        eType="#//RequestPayload"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dto"
        upperBound="-1"
        eType="#//Dto"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dbentity"
        upperBound="-1"
        eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Controller">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="restinterface"
        upperBound="-1"
        eType="#//RestInterface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RestInterface">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="requestpayload"
        eType="#//RequestPayload"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="responseresult"
        eType="#//ResponseResult"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="restApiUri"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="apiDesc"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bizservice"
        upperBound="-1"
        eType="#//BizService"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Dto">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dto"
        upperBound="-1"
        eType="#//Dto"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dtoattr"
        upperBound="-1"
        eType="#//DtoAttr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Service">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BizService"
      eSuperTypes="#//Service">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="baseservice"
        upperBound="-1"
        eType="#//BaseService"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BaseService"
      eSuperTypes="#//Service">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="repo"
        upperBound="-1"
        eType="#//Repo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="RequestPayload">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="generatedBy"
        lowerBound="1"
        eType="#//DomainEntity"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="requestattr"
        upperBound="-1"
        eType="#//RequestAttr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DbEntity">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dbattr"
        lowerBound="1"
        upperBound="-1"
        eType="#//DbAttr"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="domainentity"
        upperBound="-1"
        eType="#//DomainEntity"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ResponseResult">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="responseattr"
        upperBound="-1"
        eType="#//ResponseAttr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Repo">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="dbentity"
        lowerBound="1"
        eType="#//DbEntity"/>
  </eClassifiers>
</ecore:EPackage>
