<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hyldesigner" nsURI="http://mdse.hylstudio.cn/hyldesigner" nsPrefix="hyldesigner">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageRoot" lowerBound="1"
        eType="#//PackageDefine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainEntities" upperBound="-1"
        eType="#//DomainEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dbEntities" upperBound="-1"
        eType="#//DbEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reqPayloads" upperBound="-1"
        eType="#//RequestPayload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respResults" upperBound="-1"
        eType="#//ResponseResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//PrimitiveType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDefine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//PackageDefine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainEntities" upperBound="-1"
        eType="#//DomainEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestPayloads" upperBound="-1"
        eType="#//RequestPayload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseResults" upperBound="-1"
        eType="#//ResponseResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//Dto"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//PrimitiveType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refUserDefinedCheckRules"
        upperBound="-1" eType="#//check/UserDefinedCheckRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstracVar" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true" eSuperTypes="#//VarDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attr" abstract="true" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrDomainCheckRules" upperBound="-1"
        eType="#//check/DomainEntityCheckRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrReferencedCheckRules"
        upperBound="-1" eType="#//check/ReferencedCheckRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//VarDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarDef" eSuperTypes="#//AbstracVar"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//VarDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttr" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBizKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needPersistent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestAttr" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrRef" eType="#//DomainAttr"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="DtoAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//DomainAttr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedDto" upperBound="-1"
        eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedDbEntity" upperBound="-1"
        eType="#//DbEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainCheckRules" upperBound="-1"
        eType="#//check/DomainEntityCheckRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userDefinedCheckRules"
        upperBound="-1" eType="#//check/UserDefinedCheckRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" lowerBound="1" upperBound="-1"
        eType="#//Attr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" upperBound="-1"
        eType="#//DomainEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestPayload" eSuperTypes="#//ReferencedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payloadRef" eType="#//DomainEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseResult" eSuperTypes="#//ReferencedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dto" eSuperTypes="#//ReferencedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDto" lowerBound="1"
        upperBound="-1" eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDomainEntity"
        lowerBound="1" upperBound="-1" eType="#//DomainEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDbEntity" lowerBound="1"
        upperBound="-1" eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappings" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restInterface" upperBound="-1"
        eType="#//RestInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methods" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappings" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceMainFlow" eType="#//control/ControlFlow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//RestInterfaceResponse"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestInterfaceResponse" eSuperTypes="#//VarRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" eSuperTypes="#//ReferencedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BizService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokeBase" upperBound="-1"
        eType="#//BaseService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessRepo" upperBound="-1"
        eType="#//Repo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repo" eSuperTypes="#//ReferencedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeEntity" lowerBound="1"
        eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainFlow" eType="#//control/ControlFlow"
        containment="true"/>
  </eClassifiers>
  <eSubpackages name="control" nsURI="http://mdse.hylstudio.cn/hyldesigner/control"
      nsPrefix="control">
    <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
          eType="#//VarRef" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//control/OperationResult"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationResult" eSuperTypes="#//VarDef"/>
    <eClassifiers xsi:type="ecore:EClass" name="InvokeService" eSuperTypes="#//control/Operation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="async" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
          eType="#//control/ControlFlow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//control/ControlFlow">
      <eStructuralFeatures xsi:type="ecore:EReference" name="do" upperBound="-1" eType="#//control/Operation"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="check" nsURI="http://mdse.hylstudio.cn/hyldesigner/check" nsPrefix="check">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractCheckRule" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainEntityCheckRule" abstract="true"
        eSuperTypes="#//check/AbstractCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferencedCheckRule" abstract="true"
        eSuperTypes="#//check/AbstractCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="UserDefinedCheckRule" abstract="true"
        eSuperTypes="#//check/AbstractCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="CustomCheckRule" abstract="true" eSuperTypes="#//check/UserDefinedCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeCheckRule" abstract="true"
        eSuperTypes="#//check/DomainEntityCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReferencedTypeCheckRule" abstract="true"
        eSuperTypes="#//check/ReferencedCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringTypeCheckRule" abstract="true"
        eSuperTypes="#//check/PrimitiveTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NotEmptyCheckRule" eSuperTypes="#//check/StringTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="LengthCheckRule" eSuperTypes="#//check/StringTypeCheckRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RegexCheckRule" eSuperTypes="#//check/StringTypeCheckRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberTypeCheckRule" abstract="true"
        eSuperTypes="#//check/PrimitiveTypeCheckRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeCheckRule" abstract="true"
        eSuperTypes="#//check/NumberTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="LongTypeCheckRule" abstract="true"
        eSuperTypes="#//check/NumberTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerRangeCheckRule" eSuperTypes="#//check/IntegerTypeCheckRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LongRangeCheckRule" eSuperTypes="#//check/LongTypeCheckRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BoolTypeCheckRule" abstract="true"
        eSuperTypes="#//check/PrimitiveTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="TrueValueCheckRule" eSuperTypes="#//check/BoolTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FalseValueCheckRule" eSuperTypes="#//check/BoolTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="DtoTypeCheckRule" abstract="true"
        eSuperTypes="#//check/ReferencedTypeCheckRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="HasValueRefCheckRule" eSuperTypes="#//check/ReferencedTypeCheckRule"/>
  </eSubpackages>
</ecore:EPackage>
