<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hyldesigner" nsURI="http://mdse.hylstudio.cn/hyldesigner" nsPrefix="hyldesigner">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageRoot" lowerBound="1"
        eType="#//PackageDefine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainEntities" upperBound="-1"
        eType="#//DomainEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dbEntities" upperBound="-1"
        eType="#//DbEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reqPayloads" upperBound="-1"
        eType="#//RequestPayload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respResults" upperBound="-1"
        eType="#//ResponseResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDefine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//PackageDefine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainEntities" upperBound="-1"
        eType="#//DomainEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestPayloads" upperBound="-1"
        eType="#//RequestPayload" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseResults" upperBound="-1"
        eType="#//ResponseResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//Dto"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attr" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objType" eType="#//Attr"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttr" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBizKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needPersistent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="DtoAttr" eSuperTypes="#//Attr"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//DomainAttr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedPayload" upperBound="-1"
        eType="#//RequestPayload"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedDto" upperBound="-1"
        eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedDbEntity" upperBound="-1"
        eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappings" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restInterface" upperBound="-1"
        eType="#//RestInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methods" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappings" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payload" eType="#//RequestPayload"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ResponseResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processBlock" lowerBound="1"
        eType="#//ProcessBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dto" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refer" eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDto" lowerBound="1"
        upperBound="-1" eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDomainEntity"
        lowerBound="1" upperBound="-1" eType="#//DomainEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedByDbEntity" lowerBound="1"
        upperBound="-1" eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BizService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokeBase" upperBound="-1"
        eType="#//BaseService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseService" eSuperTypes="#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessRepo" upperBound="-1"
        eType="#//Repo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestPayload" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" lowerBound="1"
        eType="#//DomainEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseResult" eSuperTypes="#//Attr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" lowerBound="1"
        eType="#//DomainEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" upperBound="-1"
        eType="#//Attr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrs" lowerBound="1" upperBound="-1"
        eType="#//Attr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedBy" upperBound="-1"
        eType="#//DomainEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeEntity" lowerBound="1"
        eType="#//DbEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//VarDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//TypeDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TypeDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objType" eType="#//Attr"/>
  </eClassifiers>
</ecore:EPackage>
