/**
 */
package cn.hylstudio.mdse.hyldesigner;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Db Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.DbEntity#getAttr <em>Attr</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.DbEntity#getGeneratedBy <em>Generated By</em>}</li>
 * </ul>
 *
 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDbEntity()
 * @model
 * @generated
 */
public interface DbEntity extends EObject {
	/**
	 * Returns the value of the '<em><b>Attr</b></em>' containment reference list.
	 * The list contents are of type {@link cn.hylstudio.mdse.hyldesigner.DbAttr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Attr</em>' containment reference list.
	 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDbEntity_Attr()
	 * @model containment="true" required="true"
	 * @generated
	 */
	EList<DbAttr> getAttr();

	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' reference list.
	 * The list contents are of type {@link cn.hylstudio.mdse.hyldesigner.DomainEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By</em>' reference list.
	 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDbEntity_GeneratedBy()
	 * @model
	 * @generated
	 */
	EList<DomainEntity> getGeneratedBy();

} // DbEntity
