/**
 */
package cn.hylstudio.mdse.hyldesigner;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.Dto#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.Dto#getGenerated <em>Generated</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.Dto#getAttr <em>Attr</em>}</li>
 * </ul>
 *
 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDto()
 * @model
 * @generated
 */
public interface Dto extends EObject {
	/**
	 * Returns the value of the '<em><b>Generated By</b></em>' reference list.
	 * The list contents are of type {@link cn.hylstudio.mdse.hyldesigner.Dto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated By</em>' reference list.
	 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDto_GeneratedBy()
	 * @model required="true"
	 * @generated
	 */
	EList<Dto> getGeneratedBy();

	/**
	 * Returns the value of the '<em><b>Generated</b></em>' reference list.
	 * The list contents are of type {@link cn.hylstudio.mdse.hyldesigner.Dto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generated</em>' reference list.
	 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDto_Generated()
	 * @model
	 * @generated
	 */
	EList<Dto> getGenerated();

	/**
	 * Returns the value of the '<em><b>Attr</b></em>' containment reference list.
	 * The list contents are of type {@link cn.hylstudio.mdse.hyldesigner.DtoAttr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Attr</em>' containment reference list.
	 * @see cn.hylstudio.mdse.hyldesigner.HyldesignerPackage#getDto_Attr()
	 * @model containment="true"
	 * @generated
	 */
	EList<DtoAttr> getAttr();

} // Dto
