/**
 */
package cn.hylstudio.mdse.hyldesigner.impl;

import cn.hylstudio.mdse.hyldesigner.Dto;
import cn.hylstudio.mdse.hyldesigner.DtoAttr;
import cn.hylstudio.mdse.hyldesigner.HyldesignerPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.impl.DtoImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.impl.DtoImpl#getGenerated <em>Generated</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.impl.DtoImpl#getAttr <em>Attr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DtoImpl extends MinimalEObjectImpl.Container implements Dto {
	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected EList<Dto> generatedBy;

	/**
	 * The cached value of the '{@link #getGenerated() <em>Generated</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGenerated()
	 * @generated
	 * @ordered
	 */
	protected EList<Dto> generated;

	/**
	 * The cached value of the '{@link #getAttr() <em>Attr</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getAttr()
	 * @generated
	 * @ordered
	 */
	protected EList<DtoAttr> attr;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DtoImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return HyldesignerPackage.Literals.DTO;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Dto> getGeneratedBy() {
		if (generatedBy == null) {
			generatedBy = new EObjectResolvingEList<Dto>(Dto.class, this, HyldesignerPackage.DTO__GENERATED_BY);
		}
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<Dto> getGenerated() {
		if (generated == null) {
			generated = new EObjectResolvingEList<Dto>(Dto.class, this, HyldesignerPackage.DTO__GENERATED);
		}
		return generated;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<DtoAttr> getAttr() {
		if (attr == null) {
			attr = new EObjectContainmentEList<DtoAttr>(DtoAttr.class, this, HyldesignerPackage.DTO__ATTR);
		}
		return attr;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
		case HyldesignerPackage.DTO__ATTR:
			return ((InternalEList<?>) getAttr()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
		case HyldesignerPackage.DTO__GENERATED_BY:
			return getGeneratedBy();
		case HyldesignerPackage.DTO__GENERATED:
			return getGenerated();
		case HyldesignerPackage.DTO__ATTR:
			return getAttr();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
		case HyldesignerPackage.DTO__GENERATED_BY:
			getGeneratedBy().clear();
			getGeneratedBy().addAll((Collection<? extends Dto>) newValue);
			return;
		case HyldesignerPackage.DTO__GENERATED:
			getGenerated().clear();
			getGenerated().addAll((Collection<? extends Dto>) newValue);
			return;
		case HyldesignerPackage.DTO__ATTR:
			getAttr().clear();
			getAttr().addAll((Collection<? extends DtoAttr>) newValue);
			return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
		case HyldesignerPackage.DTO__GENERATED_BY:
			getGeneratedBy().clear();
			return;
		case HyldesignerPackage.DTO__GENERATED:
			getGenerated().clear();
			return;
		case HyldesignerPackage.DTO__ATTR:
			getAttr().clear();
			return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
		case HyldesignerPackage.DTO__GENERATED_BY:
			return generatedBy != null && !generatedBy.isEmpty();
		case HyldesignerPackage.DTO__GENERATED:
			return generated != null && !generated.isEmpty();
		case HyldesignerPackage.DTO__ATTR:
			return attr != null && !attr.isEmpty();
		}
		return super.eIsSet(featureID);
	}

} //DtoImpl
