/**
 */
package cn.hylstudio.mdse.hyldesigner.impl;

import cn.hylstudio.mdse.hyldesigner.DomainEntity;
import cn.hylstudio.mdse.hyldesigner.HyldesignerPackage;
import cn.hylstudio.mdse.hyldesigner.RequestAttr;
import cn.hylstudio.mdse.hyldesigner.RequestPayload;

import java.util.Collection;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Request Payload</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.impl.RequestPayloadImpl#getGeneratedBy <em>Generated By</em>}</li>
 *   <li>{@link cn.hylstudio.mdse.hyldesigner.impl.RequestPayloadImpl#getRequestattr <em>Requestattr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RequestPayloadImpl extends MinimalEObjectImpl.Container implements RequestPayload {
	/**
	 * The cached value of the '{@link #getGeneratedBy() <em>Generated By</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGeneratedBy()
	 * @generated
	 * @ordered
	 */
	protected DomainEntity generatedBy;

	/**
	 * The cached value of the '{@link #getRequestattr() <em>Requestattr</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRequestattr()
	 * @generated
	 * @ordered
	 */
	protected EList<RequestAttr> requestattr;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequestPayloadImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return HyldesignerPackage.Literals.REQUEST_PAYLOAD;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public DomainEntity getGeneratedBy() {
		if (generatedBy != null && generatedBy.eIsProxy()) {
			InternalEObject oldGeneratedBy = (InternalEObject) generatedBy;
			generatedBy = (DomainEntity) eResolveProxy(oldGeneratedBy);
			if (generatedBy != oldGeneratedBy) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE,
							HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY, oldGeneratedBy, generatedBy));
			}
		}
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DomainEntity basicGetGeneratedBy() {
		return generatedBy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setGeneratedBy(DomainEntity newGeneratedBy) {
		DomainEntity oldGeneratedBy = generatedBy;
		generatedBy = newGeneratedBy;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY,
					oldGeneratedBy, generatedBy));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<RequestAttr> getRequestattr() {
		if (requestattr == null) {
			requestattr = new EObjectContainmentEList<RequestAttr>(RequestAttr.class, this,
					HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR);
		}
		return requestattr;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
		case HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR:
			return ((InternalEList<?>) getRequestattr()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
		case HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY:
			if (resolve)
				return getGeneratedBy();
			return basicGetGeneratedBy();
		case HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR:
			return getRequestattr();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
		case HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY:
			setGeneratedBy((DomainEntity) newValue);
			return;
		case HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR:
			getRequestattr().clear();
			getRequestattr().addAll((Collection<? extends RequestAttr>) newValue);
			return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
		case HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY:
			setGeneratedBy((DomainEntity) null);
			return;
		case HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR:
			getRequestattr().clear();
			return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
		case HyldesignerPackage.REQUEST_PAYLOAD__GENERATED_BY:
			return generatedBy != null;
		case HyldesignerPackage.REQUEST_PAYLOAD__REQUESTATTR:
			return requestattr != null && !requestattr.isEmpty();
		}
		return super.eIsSet(featureID);
	}

} //RequestPayloadImpl
